### ISSUE TITLE
advanced_turtle.lua:692: bad argument #1 (value expected)

### ISSUE THREAD

**Issue by CavemanTechandGamming** [Calame321/TurtleFleet#2]
![2022-08-16_16 23 05](https://user-images.githubusercontent.com/71993043/184978142-f66d71eb-ae30-4fb6-8c08-4840e1e25343.png)
advanced_turtle.lua:692: bad argument #1 (value expected)
I am using it in the Direwolf20 ftb mod pack Minecraft version 1.18.2

It worked fine for 2 days the today it quit working I deleted it and redownloaded it to see if that fixed it and tried a different turtle and it is still not working

**Comment by Calame321** [comment]
It might be the "resume job" feature that cause the problem.
I'm going to remove it for now, I'll bring it back once it's more reliable.
For a quick fix, you can stop the turtle with ( hold, Ctrl + T for 3 sec ) or press the button to stop the code. then type "delete job".

**Comment by CavemanTechandGamming** [comment]
Okay, I tried stopping the code and then typing "delete job" and it says no such program found and when I turn the turtle back on it throws the same error code again.

**Comment by Calame321** [comment]
Type delete job without the " quotes.

**Comment by CavemanTechandGamming** [comment]
i did

**Comment by CavemanTechandGamming** [comment]
I really do appreciate you taking the time to look into it. And I'm glad to see you maintaining your script after it was posted for almost a year. Plenty of other scripts out there don't work half as well because they weren't maintained.

**Comment by Calame321** [comment]
I always wanted to create a big software for those little Turtle haha. It's a little side project that I come back to when I play some modded Minecraft.

The update is there, let me know if you encounter any bug!
