### ISSUE TITLE
Found a few things so far.

### ISSUE THREAD

**Issue by CavemanTechandGamming** [Calame321/TurtleFleet#3]
When you run the install from pastebin it says that it cannot find some of the files that it is looking for.
[Clip here.](https://youtu.be/u7XIAGSr3EQ)

If you set Turtles requiring fuel to false in server configuration files for your game they will not function and throw an error.
advanced_turtle.lua:897: attempt to compare string with number
[Clip here.](https://youtu.be/fNV3zimg-2c)

Throws an error when it comes across an ore when running branch mine.
Miner.lua:195: attempt to get length of field ‘DO_NOT_MINE’ (a nil value)
[Clip here.](https://youtu.be/4B_1wMhVE4o)

If I find any other errors I'll let you know.

**Comment by Calame321** [comment]
Thx a lot for the clips!
- Removed unused file in the installer.
- I added support for the turtle not using fuel.
- Fixed the DO_NOT_MINE.
