### ISSUE TITLE
bios.lua:544: Failed to load API computer_startup due to file not found

### ISSUE THREAD

**Issue by CavemanTechandGamming** [Calame321/TurtleFleet#4]
Found this today. 

https://user-images.githubusercontent.com/71993043/186545253-9b06e0bc-61fe-4f70-9859-725f657858b9.mp4

You are welcome for the clips. I'm sorry I couldn't get them small enough to just put here last time.

**Comment by CavemanTechandGamming** [comment]
It's looking for a program without the .lua pension but if you add the .lua extension to the startup file that works.

**Comment by CavemanTechandGamming** [comment]
It's working now. I saw that you updated it so I reinstalled it and it works.

**Comment by Calame321** [comment]
Haha! It's fixed. You can't use the computer for anything yet but, it's still in the the plan for future update XD. I changed the pastebin code so it's a nice little installer now. will improve more soon.
